---
  title: "Independent and Identically Distributed"
output: 'pdf_document'  
classoption: landscape
fontsize: 12pt
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(wooldridge)
library(car)
library(lmtest)
library(sandwich)
library(stargazer)
```

## How the data was sourced
The data was scraped from the YouTube lists, "Recently Featured", "Most Viewed", "Top Rated" and "Most Discussed", for "Today", "This Week", "This Month" and "All Time" where the crawler was run in rates of 2-3 days. As a result of these types of lists, there is an issue with IID since there would be more representation of recent videos. This would mean that one datapoint (video) can inform features of another video. 
An couple examples of how this could manifest is:
- Since the scraped videos are on top lists, this would mean that these videos inform of each other since they are already popular. One could speculate they are gaining more views because of endorsements, marketing or professional editing.
- Perhaps a particularly trending topic is attracting a lot of view attention. Due it a video being related to that topic at the time, these videos can inform other videos that are within the same topic. 

